---
- name: My Test Copy Playbook
  hosts: all
  become: true
  tasks:
  - name: Copying file
    copy:
      src: /home/ansadmin/Ansible/index.html
      dest: /home/ansadmin/index.html
      mode: 0777
      owner: rohit
...
