---
- name: Playbook to create multiple users
  hosts: all
  become: yes
  tasks:
  - name: Create multiple users
    user: name='{{ item }}' state=present
    with_items:
    - Sai
    - Suraj
    - Om
