---
- name: Playbook to setup Tomcat application
  hosts: all
  become: true
  tasks:
  - name: Install java package on RedHat
    yum:
      name: java
      state: present
    when: ansible_os_family == "RedHat"

  - name: Install java package on Debian
    apt:
      name: java
      state: present
    when: ansible_os_family == "Debian"
 
  - name: Download package tar file
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.97/bin/apache-tomcat-9.0.97.tar.gz
      dest: /opt

  - name: extract package from zip file
    unarchive:
      src: /opt/apache-tomcat-9.0.97.tar.gz
      dest: /opt
      remote_src: yes

  - name: change file permissions
    file:
      path: /opt/apache-tomcat-9.0.97/bin/startup.sh
      mode: 0777

  - name: start tomcat service
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-9.0.97/bin
...
